/opt/xray-node/logs/*.log {
    daily
    rotate 7
    compress
    compresscmd /usr/bin/zstd
    compressext .zst
    compressoptions -19 --rm
    delaycompress
    missingok
    notifempty
    sharedscripts
    postrotate
        docker kill --signal=USR1 xray
    endscript
}
